version: '3'

services:
  flask:
    build: ./app
    ports:
      - "8080:8080"
    command: gunicorn --bind 0.0.0.0:8080 --workers 1 "application:app"
    volumes:
      - dbdata:/user
volumes:
  dbdata:
